### ISSUE TITLE
Flutter_Blue background scanning with flutter_isolate

### ISSUE THREAD

**Issue by MichealReed** [rmawatson/flutter_isolate#19]
For some reason, I cannot get flutter blue to scan properly when placed in an isolate. It initiates the scanning process, but no results are ever returned. I have tried to separate the scanning into the foreground and access/connect to the device in the background, but it results in a null reference error because I am attempting to access memory out of scope. The screenshot below uses @rmawatson's PR https://github.com/pauldemarco/flutter_blue/pull/191, but I have also experienced this after merging the necessary changes from this PR with the latest from flutter_blue master.

Console output: 

![image](https://user-images.githubusercontent.com/12153323/62553750-86736e00-b835-11e9-9567-10b724a0ea89.png)

![image](https://user-images.githubusercontent.com/12153323/62553212-8c1c8400-b834-11e9-90d7-2dd902b044fa.png)

``` static void isolate1(SendPort arg) async {
    print('test1');
    BluetoothDevice device;
    
    FlutterBlue.instance.scan(timeout: Duration(seconds: 4), withServices: [new Guid('0000180D-0000-1000-8000-00805F9B34FB')]).listen((scanResult){
      device = scanResult.device;
      print(device.name);
    });
    print('test2');
      try{
      FlutterBlue.instance.connect(device).listen((s){ });
      }catch(e)
      {print("Already connected!");}
      var services = await device.discoverServices();
      for (var service in services) {
        if (service.uuid.toString() == "0000180d-0000-1000-8000-00805f9b34fb") {
          var characteristics = service.characteristics;
          for (BluetoothCharacteristic c in characteristics) {
            List<int> value = await device.readCharacteristic(c);
            print(service.uuid.toString());
            print(c.uuid.toString());
            if (c.uuid.toString() == "00002a37-0000-1000-8000-00805f9b34fb") {
              await device.setNotifyValue(c, true);
              device.onValueChanged(c).listen((value) {
                var date = new DateTime.now().millisecondsSinceEpoch;
              });
            }
        }
      }
    }
  }

  @override
  Stream<AppBluetoothState> mapEventToState(BluetoothEvent event) async* {
    if (event is StartBluetoothScanEvent) {
      var instance = FlutterBlue.instance;

      ReceivePort receivePort = ReceivePort();
      receivePort.listen((data) {

      });
      await FlutterIsolate.spawn(isolate1, receivePort.sendPort);
    }

**Comment by MichealReed** [comment]
Was able to get this working with @rmawatson's PR, but not for my merges. There is also an issue with flutter that makes this only compatible with earlier releases. I am using v1.5.3.

**Comment by vikramkapoor** [comment]
@MichealReed 
Any luck with this? I am stuck not being able run a scan from an Isolate. My application requires Bluetooth to run in background.
I merged latest changes from pauldemarco/flutter_blue into rmwatson/flutter_blue. in my fork vikramkapoor/flutter_blue. The scan results in a crash when run from an Isolate.

09-03 18:23:17.630 5117-5117/com.rakshak.safeho E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.rakshak.safeho, PID: 5117
    java.lang.NullPointerException: Attempt to invoke virtual method 'void android.app.Activity.runOnUiThread(java.lang.Runnable)' on a null object reference
        at com.pauldemarco.flutterblue.FlutterBluePlugin.invokeMethodUIThread(FlutterBluePlugin.java:854)
        at com.pauldemarco.flutterblue.FlutterBluePlugin.access$200(FlutterBluePlugin.java:58)
        at com.pauldemarco.flutterblue.FlutterBluePlugin$2.onScanResult(FlutterBluePlugin.java:649)
        at android.bluetooth.le.BluetoothLeScanner$BleScanCallbackWrapper$1.run(BluetoothLeScanner.java:355)
        at android.os.Handler.handleCallback(Handler.java:743)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:171)
        at android.app.ActivityThread.main(ActivityThread.java:5417)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
09-03 18:23:17.630 5117-5117/com.rakshak.safeho E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.rakshak.safeho, PID: 5117
    java.lang.NullPointerException: Attempt to invoke virtual method 'void android.app.Activity.runOnUiThread(java.lang.Runnable)' on a null object reference
        at com.pauldemarco.flutterblue.FlutterBluePlugin.invokeMethodUIThread(FlutterBluePlugin.java:854)
        at com.pauldemarco.flutterblue.FlutterBluePlugin.access$200(FlutterBluePlugin.java:58)
        at com.pauldemarco.flutterblue.FlutterBluePlugin$2.onScanResult(FlutterBluePlugin.java:649)
        at android.bluetooth.le.BluetoothLeScanner$BleScanCallbackWrapper$1.run(BluetoothLeScanner.java:355)
        at android.os.Handler.handleCallback(Handler.java:743)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:171)
        at android.app.ActivityThread.main(ActivityThread.java:5417)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by MichealReed** [comment]
Just got this working last night. I'm mobile, so it's hard to link directly, but my fork should have the latest. It still doesn't keep things alive forever in the background though, so if you get any ideas on that front let me know.

- Micheal

________________________________

**Comment by vikramkapoor** [comment]
Previously it used to stay alive in the Isolate even with screen off but now it stops working as soon as the screen is turned off on Android. It works fine on iOS. I will keep investigating.
Vikram 
    On Wednesday, September 4, 2019, 07:15:01 AM PDT, MichealReed <notifications@github.com> wrote:  
 
 Just got this working last night. I'm mobile, so it's hard to link directly, but my fork should have the latest. It still doesn't keep things alive forever in the background though, so if you get any ideas on that front let me know.

- Micheal

________________________________

**Comment by vikramkapoor** [comment]
It seems to work fine in the background on iPhone. Just on Android it stops receiving events when the phone screen is off. We need to make sure the application is running in doze mode.

**Comment by vikramkapoor** [comment]
@MichealReed 

I now have Flutter_blue working fine . when phone screen is off and phone is not plugged in. The only change I did was to move Flutter_blue interface from background_isolate to the main UI thread of my app. See example code below of how I register for button press notifications from the device after it connects.

```
              StreamBuilder<List<ScanResult>>(
                stream: FlutterBlue.instance.scanResults,
                initialData: [],
                builder: (c, snapshot) => Column(
                  children: snapshot.data
                      .map(
                        (r) => ScanResultTile(
                      result: r,
                      onTap: () => Navigator.of(context).push(
                          MaterialPageRoute(builder: (context) {
                            r.device.connect().then((c){
                      r.device.discoverServices().then((services) {
                        //Register for button press notification
                
                        for (BluetoothService service in services) {
                          for (BluetoothCharacteristic c
                          in service.characteristics) {
                            if (c.uuid ==
                                new Guid(
                                    "0000ffe1-0000-1000-8000-00805f9b34fb")) {
                              debugPrint("Button: isNotifying = ${c.isNotifying}");
                              if (c.isNotifying != true) {
                              debugPrint(
                                  "Button: Register for button press notification");
                              int ignoreCount = 1;
                              c.setNotifyValue(true); 
                              c.value.listen((value) {
                                if (_debounce?.isActive ?? false) _debounce
                                    .cancel();
                                _debounce =
                                    Timer(
                                        const Duration(milliseconds: 200), () {
                                      value.forEach((f) {
                                        debugPrint(
                                            "Button press value = $f");
                                      });
                                      c.lastValue.forEach((f) {
                                        debugPrint(
                                            "Button press last value = $f");
                                      });
                                      if (ignoreCount != 0)
                                        ignoreCount--;
                                      else {
                                          debugPrint("Button pressed");
                                          Globals.receivePort.sendPort.send("Panic button pressed");
                                        }
                                      },
                                    );
                              });
                              // Add to map
                              print(
                                  "Notifications set on bluetooth button press");
                               }
                            }
                          }
                        }
                      });
                      });
                            return DeviceScreen(device: r.device);
                          })),
                    ),
                  )
                      .toList(),
                ),
              ),
            ],
          ),
        ),
      ),
'''

**Comment by BalanaguYashwanth** [comment]
Can Any body  give github link for above code please....................

**Comment by FilipeLarga** [comment]
Hey @vikramkapoor, @MichealReed. Could you provide some more insight into what is the solution? Are you still running the code in an isolate? I can't seem to understand your solution.

**Comment by flutterboi** [comment]
Any update on this?

**Comment by Ozzy340** [comment]
I'm experiencing a similar flutter_blue running in the background isolate problem. Explanation of the solution or example code would be very useful.

**Comment by vikramkapoor** [comment]
I am not running any code in background isolate anymore.

**Comment by Ozzy340** [comment]
@vikramkapoor I assume this is unlikely to work for scanning of Bluetooth devices in the background while the device screen is off?

**Comment by ramashish-headerlabs** [comment]
i want to scan for the ble devices even if the phone screen is off/locked or app in background then send data to backend.
is there any way i can do it

**Comment by Ozzy340** [comment]
> i want to scan for the ble devices even if the phone screen is off/locked or app in background then send data to backend.
> is there any way i can do it

I currently building something to achieve exactly this. From my research so far, to truly work in the background (and not just be disabled after Xnumber of minutes it requires platform-specific code to be added.

**Comment by ramashish-headerlabs** [comment]
if it is set to work for a few minutes that too will we a relief

**Comment by Ozzy340** [comment]
> if it is set to work for a few minutes that too will be a relief

the thread doesn't get destroyed immediately after you move away from the app, however there is little to know exactly how long it will last (as it is dependent on a number of external conditions).

I haven't had much success with flutter isolates to run Flutter blue (I got the impression at one point these two were compatible but it would seem no longer).

**Comment by nmfisher** [comment]
At the moment flutter_blue won't work from a spawned isolate I'm afraid. I'll close this for now in favour of https://github.com/rmawatson/flutter_isolate/issues/71 where we can track progress.
